title = "Voice Assistant Config File"

[config]
CHUNK = 2048
FORMAT = "Int16"
CHANNELS = 1
RATE = 16000
THRESHOLD = 2500
SENSITIVITY = 0.45
WS = "ws://192.168.0.107:9001"
KODI = "http://192.168.0.107:8080/jsonrpc"


